[tox]
envlist =
    py311-django{42,52}

[testenv]
allowlist_externals = ./runtests.py
setenv =
    PYTHONDONTWRITEBYTECODE=1
deps =
    django42: Django>=4.2,<4.3
    django52: Django>=5.2,<5.3
    -rrequirements.txt
commands = ./runtests.py {posargs}
